# Generated by Django 5.2.8 on 2026-03-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, help_text='Opcional. Link para onde o usuário será levado ao clicar.', null=True, verbose_name='Link de Redirecionamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner da Dashboard',
                'verbose_name_plural': 'Banners da Dashboard',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
