# Generated by Django 5.2.8 on 2026-03-31 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bannerdashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativar_impressao_pos_venda', models.BooleanField(default=True, verbose_name='Ativar Impressão Pós-Venda')),
                ('whatsapp_notificacao', models.BooleanField(default=False, verbose_name='Enviar Cupom via WhatsApp')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuração de Empresa',
                'verbose_name_plural': 'Configurações de Empresas',
            },
        ),
    ]
