# Generated by Django 5.2.8 on 2026-04-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracaoempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdvTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('api_key', models.CharField(editable=False, max_length=80, unique=True, verbose_name='API Key')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultimo_sync', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo Sync')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdv_terminais', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Terminal PDV',
                'verbose_name_plural': 'Terminais PDV',
                'ordering': ['identificador'],
            },
        ),
    ]
