# Generated by Django 5.0.14 on 2026-05-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pdvterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='apenas_digios_local',
            field=models.BooleanField(default=False, verbose_name='Apenas Digi-OS Local'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='chave_licenca',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Chave de Licença'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='duracao_licenca',
            field=models.CharField(blank=True, choices=[('6m', '6 Meses'), ('1y', '1 Ano'), ('2y', '2 Anos'), ('3y', '3 Anos')], max_length=2, null=True, verbose_name='Duração da Licença'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='validade_licenca',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validade da Licença'),
        ),
    ]
