# Generated by Django 5.0.14 on 2026-05-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pdvterminal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerdashboard',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='bannerdashboard',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='bannerdashboard',
            name='imagem',
            field=models.ImageField(help_text='Tamanho recomendado para a imagem: 1200x320 pixels (ou proporção equivalente).', upload_to='banners/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='bannerdashboard',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Redirecionamento'),
        ),
    ]
