# Generated by Django 5.0.14 on 2026-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_bannerdashboard_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='chave_licenca',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='duracao_licenca',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='validade_licenca',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('operador', 'Operador')], default='operador', max_length=20, verbose_name='Perfil'),
        ),
    ]
