# Generated by Django 5.0.14 on 2026-05-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_perfilusuario_chave_licenca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='impressao_automatica_pdv',
            field=models.BooleanField(default=False, verbose_name='Impressão Automática PDV'),
        ),
    ]
