# Generated by Django 5.0.14 on 2026-05-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_configuracaoempresa_impressao_automatica_pdv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='apenas_digios_local',
        ),
    ]
