# Generated by Django 5.2.8 on 2026-03-27 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('aguardando_peca', 'Aguardando Peça'), ('pronta', 'Pronta'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('equipamento', models.CharField(max_length=200, verbose_name='Equipamento')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('defeito_reclamado', models.TextField(verbose_name='Defeito Reclamado')),
                ('defeito_constatado', models.TextField(blank=True, verbose_name='Defeito Constatado')),
                ('solucao', models.TextField(blank=True, verbose_name='Solução Aplicada')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Data Prevista')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('valor_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor dos Serviços')),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor das Peças')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('garantia_dias', models.PositiveIntegerField(default=30, verbose_name='Garantia (dias)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='core.empresa')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servico', 'Serviço'), ('peca', 'Peça')], default='servico', max_length=10, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Item de OS',
                'verbose_name_plural': 'Itens de OS',
            },
        ),
    ]
