# Generated by Django 5.2.8 on 2026-03-27 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_produto', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço')], default='produto', max_length=10, verbose_name='Tipo')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('unidade', models.CharField(default='UN', max_length=10, verbose_name='Unidade')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço de Venda')),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Estoque Atual')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Estoque Mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoriaproduto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
