# Generated by Django 5.0.14 on 2026-05-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_categoria_delete_categoriaproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
