# Generated by Django 5.0.14 on 2026-05-12 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\d{0,13}$', 'O código de barras deve conter apenas números e no máximo 13 dígitos.')], verbose_name='Código de Barras'),
        ),
    ]
