# Generated by Django 5.2.17 on 2026-09-28 12:25

import produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_movimentoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=produtos.models.caminho_imagem_produto, verbose_name='Imagem'),
        ),
    ]
