# Generated by Django 5.0.14 on 2026-05-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_remove_empresa_apenas_digios_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2, verbose_name='Tipo de Pessoa')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, verbose_name='CPF / CNPJ')),
                ('telefone1', models.CharField(blank=True, max_length=20, verbose_name='Telefone 1')),
                ('telefone2', models.CharField(blank=True, max_length=20, verbose_name='Telefone 2')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
    ]
