# Generated by Django 5.2.8 on 2026-03-30 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='emissao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data Emissão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contapagar',
            name='numero_titulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº Título'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='parcela',
            field=models.CharField(default='1/1', max_length=10, verbose_name='Parcela'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='emissao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data Emissão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contareceber',
            name='numero_titulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº Título'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='parcela',
            field=models.CharField(default='1/1', max_length=10, verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15, verbose_name='Status'),
        ),
    ]
