# Generated by Django 5.0.14 on 2026-05-09 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_contapagar_desconto_contapagar_emissao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaixaContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_pagamento', models.DateField(verbose_name='Data de Pagamento')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('transferencia', 'Transferência'), ('boleto', 'Boleto'), ('cheque', 'Cheque')], max_length=20, verbose_name='Forma de Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='financeiro.contapagar')),
            ],
            options={
                'verbose_name': 'Baixa de Conta a Pagar',
                'verbose_name_plural': 'Baixas de Contas a Pagar',
            },
        ),
    ]
